### PR TITLE
Add jquery before other scripts

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
I tried to add it to this line:
https://github.com/Robert-Frampton/generator-electric/blob/lexicon/generators/quartz/templates/gulpfile.js#L54

But the load order cannot be controlled,  jquery was loaded after bootstrap, so bootstrap did not work

**Comment by robframpton** [comment]
Hey @marcoscv-work 

I went ahead and merged this. But we should be able to remove it once we update the `quartz` theme to use `electric@2.0.0-alpha`, we've made some improvements on how to add vendor scripts/styles.

**Comment by marcoscv-work** [comment]
I see, sounds good.

We are gonna use this current version of electric to create Lexicon (user experience) Site.
Any advice? should we stop this task?

Thanks Rob!

**Comment by robframpton** [comment]
The changes will be pretty minimal to your site, and I can send you a pull request for them. So it shouldn't be a problem.

**Pull request merged**
